# Generated by Django 4.2.2 on 2023-07-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Иконка')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название сайта')),
                ('iconMenu', models.ImageField(default='', upload_to='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePage', models.CharField(default='', max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Отображение в браузере')),
            ],
        ),
        migrations.CreateModel(
            name='UpperSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='верхний слайдер')),
                ('description', models.TextField(default='', unique=True, verbose_name='описание слайдера')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Текст меню')),
                ('related_Page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_application.page', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='your title', max_length=300)),
                ('text', models.TextField(blank=True, default='your text')),
                ('image', models.ImageField(blank=True, upload_to='InfoBanner')),
                ('image1', models.ImageField(blank=True, upload_to='InfoBanner')),
                ('page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_application.page')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название блюда')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Описание блюда, состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(default='', upload_to='dishs/', verbose_name='Фото блюда')),
                ('currency', models.CharField(choices=[('₽', 'RUB'), ('$', 'USD'), ('€', 'EUR')], default='Rub', max_length=3, verbose_name='Валюта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.category')),
                ('related_Page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_application.page')),
            ],
        ),
    ]
