# Generated by Django 4.2.2 on 2023-07-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='your title', max_length=300)),
                ('text', models.TextField(blank=True, default='your text')),
                ('image', models.ImageField(blank=True, upload_to='InfoBanner')),
                ('page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_application.page')),
            ],
        ),
    ]
