# Generated by Django 4.2.2 on 2023-07-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='Отображение в браузере'),
        ),
        migrations.AlterField(
            model_name='upperslider',
            name='related_Page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upper_sliders', to='main_application.page'),
        ),
    ]
