# Generated by Django 4.2.2 on 2023-07-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Отображение в браузере'),
        ),
    ]
