# Generated by Django 4.2.2 on 2023-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', upload_to='dishs/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='', max_length=3),
        ),
    ]
