# Generated by Django 4.2.2 on 2023-07-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='page_images/', verbose_name='Изображение страницы'),
        ),
        migrations.AlterField(
            model_name='upperslider',
            name='related_Page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upper_sliders', to='main_application.page', to_field='slug'),
        ),
    ]
