# Generated by Django 4.2.2 on 2023-06-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_dish_image_alter_dish_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related_category',
        ),
        migrations.AddField(
            model_name='upperslider',
            name='related_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_application.upperslider'),
        ),
    ]
