# Generated by Django 4.2.2 on 2023-07-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_infobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobanner',
            name='image1',
            field=models.ImageField(blank=True, upload_to='InfoBanner'),
        ),
    ]
