# Generated by Django 4.2.2 on 2023-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_remove_category_related_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='desption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
