# Generated by Django 4.2.2 on 2023-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_infobanner_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Отображение в браузере'),
        ),
    ]
