# Generated by Django 4.2.2 on 2023-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0006_remove_page_namepage1_page_url_alter_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='namePage1',
            field=models.CharField(default='', max_length=100, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Отображение в браузере'),
        ),
    ]
