# Generated by Django 4.2.2 on 2023-06-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0006_remove_category_title_dishtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
