# Generated by Django 4.2.2 on 2023-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0007_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='dish',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Описание категории меню'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Названиие категории'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание блюда, состав'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', upload_to='dishs/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Названиие блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='upperslider',
            name='description',
            field=models.TextField(default='', unique=True, verbose_name='описание слайдера'),
        ),
        migrations.AlterField(
            model_name='upperslider',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='верхний слайдер'),
        ),
        migrations.DeleteModel(
            name='DishTitle',
        ),
    ]
