# Generated by Django 4.2.2 on 2023-07-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0007_remove_page_url_page_namepage1_alter_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='namePage1',
        ),
    ]
