# Generated by Django 4.2.2 on 2023-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0008_remove_category_title_dish_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание категории меню'),
        ),
    ]
