# Generated by Django 4.2.2 on 2023-07-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0009_remove_dish_title_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.CreateModel(
            name='DishTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Описание категории меню')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.category')),
            ],
        ),
    ]
