# Generated by Django 4.2.2 on 2023-07-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0009_rename_namepage_page_related_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='related_Page',
            new_name='namePage',
        ),
    ]
